Add `deploy_builtin_ansible_playbook` flag
claranet/terraform-azurerm-bastion-vm pull request #2
Opened 2023-01-13 10:36 UTC by taoufik07

2023-01-13 15:42 UTC, Shr3ps requested changes

2023-01-13 15:42 UTC, Shr3ps commented on r-vm-ansible.tf
> +  for_each = toset(var.deploy_builtin_ansible_playbook ? ["enabled"] : [])
Can you add `moved` blocks, so the users will not have state changes to do?

2023-01-13 15:52 UTC, taoufik07 commented on r-vm-ansible.tf
> +  for_each = toset(var.deploy_builtin_ansible_playbook ? ["enabled"] : [])
done

2023-01-16 07:48 UTC, BzSpi commented on r-vm-ansible.tf
> +  for_each = toset(var.deploy_builtin_ansible_playbook ? ["enabled"] : [])
There's no need for `moved` block for data source, no ?

2023-01-16 15:42 UTC, taoufik07 commented on r-vm-ansible.tf
> +  for_each = toset(var.deploy_builtin_ansible_playbook ? ["enabled"] : [])
I think it's only necessary for `"null_resource" "ansible_bootstrap_vm"` -- terraform will try to update the state of other resources but that won't affect the resource, as they are only used to generate the ssh key files.

let me know if I should put the `moved` blocks back

2023-01-19 09:45 UTC, Shr3ps commented
This needs a rebase because the previous PR was merged

2023-02-09 13:11 UTC, maxpoullain approved these changes

2023-02-10 08:19 UTC, BzSpi commented
Hello @taoufik07 

I do not understand the purpose of this PR. What is the use case ? The bastion-vm module without the ansible playbook is basically the linux-vm module in my opinion.

2025-04-01 11:04 UTC, closed without merging